/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-14 05:36:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class _2_005fmember_005fok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   request.setCharacterEncoding("UTF-8");
   String userid = request.getParameter("userid");
   String userpw = request.getParameter("userpw");
   String name = request.getParameter("name");
   String hp = request.getParameter("hp");
   String email = request.getParameter("email");
   //String hobby = request.getParameter("hobby"); 여러개라 배열로 받아야함
   String hobby[] = request.getParameterValues("hobby");
   String hobbystr = "";
   for(int i = 0; i < hobby.length; i++){
      hobbystr = hobbystr + hobby[i] + " ";   // 드라이브, 등산
   }
   String ssn1 = request.getParameter("ssn1");
   String ssn2 = request.getParameter("ssn2");
   String zipcode = request.getParameter("zipcode");
   String address1 = request.getParameter("address1");
   String address2 = request.getParameter("address2");
   String address3 = request.getParameter("address3");
   
   Connection conn = null;
   PreparedStatement pstmt = null;
   
   String sql = "";
   String url = "jdbc:mysql://localhost:3306/aiclass";
   String uid = "root";
   String upw = "1234";
   
   try{
      Class.forName("com.mysql.cj.jdbc.Driver");
      conn = DriverManager.getConnection(url, uid, upw);
      if(conn != null){
         sql = "insert into tb_member(mem_userid, mem_userpw, mem_name, mem_hp, mem_email, mem_hobby, mem_ssn1, mem_ssn2, mem_zipcode, mem_address1, mem_address2, mem_address3) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
         pstmt = conn.prepareStatement(sql);
         pstmt.setString(1, userid);
         pstmt.setString(2, userpw);
         pstmt.setString(3, name);
         pstmt.setString(4, hp);
         pstmt.setString(5, email);
         pstmt.setString(6, hobbystr);
         pstmt.setString(7, ssn1);
         pstmt.setString(8, ssn2);
         pstmt.setString(9, zipcode);
         pstmt.setString(10, address1);
         pstmt.setString(11, address2);
         pstmt.setString(12, address3);
         pstmt.executeUpdate();
      }
   }catch(Exception e){
      e.printStackTrace();
   }
   

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>회원가입 완료 ! </h2>\r\n");
      out.write("    <p>아이디 : ");
      out.print(userid);
      out.write("</p>\r\n");
      out.write("    <p>이름 : ");
      out.print(name);
      out.write("</p>\r\n");
      out.write("    <p>휴대폰 번호 : ");
      out.print(hp);
      out.write("</p>\r\n");
      out.write("    <p>이메일 : ");
      out.print(email);
      out.write("</p>\r\n");
      out.write("    <p>취미 : ");
      out.print(hobbystr);
      out.write("</p>\r\n");
      out.write("    <p>주민등록번호 : ");
      out.print(ssn1);
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(ssn2);
      out.write("</p>\r\n");
      out.write("    <p>우편번호 : ");
      out.print(zipcode);
      out.write("</p>\r\n");
      out.write("    <p>주소 : ");
      out.print(address1);
      out.write("</p>\r\n");
      out.write("    <p>세부주소 : ");
      out.print(address2);
      out.write("</p>\r\n");
      out.write("    <p>참고항목 : ");
      out.print(address3);
      out.write("</p>\r\n");
      out.write("    <p><a href='./2_login.jsp'>로그인하러 가기</a></p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
